name: Sync with Upstream

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Dynatrace/easytrade.git
          
      - name: Fetch from upstream
        run: |
          git fetch upstream
          
      - name: Merge upstream changes
        run: |
          git merge upstream/main -m "Merge upstream changes from Dynatrace/easytrade"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
